# Generated by Django 2.2.1 on 2019-05-30 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
