# Generated by Django 2.2.1 on 2019-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0002_url_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
