# Generated by Django 2.2.1 on 2019-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0003_url_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='last_ip',
            field=models.TextField(default='', max_length=20),
        ),
    ]
