# Generated by Django 2.2.1 on 2019-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0004_url_last_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='last_ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
